name: "Changelog action"
description: "Updates a changelog file for projects in the oscar-system universe"

inputs:
  version:
    description: "New version number"
    required: false
  conffile:
    description: "config file path"
    required: true
  changelogfile:
    description: "Path to changelog file"
    required: true
  

outputs:
  chagenlogfile:
    description: "The updated changelog file"
    value: ""

runs:
  using: 'composite'
  steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install deps
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r "${{ github.action_path }}/requirements.txt"

    - name: "make changelog"
      id: make-changelog
      shell: bash
      env:
        CONFFILE: ${{ inputs.conffile }}
        GH_TOKEN: ${{ github.token }}
        CHANGELOGFILE: ${{ inputs.changelogfile }}
      run: "python3 ${{ github.action_path }}/release-notes.py ${{ inputs.version }}"
